In [1]:
a = 6

In [2]:
a = 8

In [3]:
import numpy as np

In [4]:
it = [3, 6, 7, 11]

In [5]:
n = np.array(it)

In [6]:
type(n)

numpy.ndarray

In [7]:
twod = np.array([[1, 2, 5], [3, 4, 7]])

twod.size

6

In [8]:
y = np.array([2, 5, 6, "77"])

In [9]:
y

array(['2', '5', '6', '77'], dtype='<U11')

In [10]:
n.shape

(4,)

In [11]:
list(range(9, 16, 2))

[9, 11, 13, 15]

In [12]:
np.arange(7, 12, 2)

array([ 7,  9, 11])

In [13]:
arr1 = np.arange(40)

In [14]:
arr2 = arr1.reshape(8, 5)

In [15]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [16]:
arr1[0] = 1000

In [17]:
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [18]:
arr1 is arr2

False